# en:
#   languageCode: en-US
#   languageName: "English"
#   weight: 2

# zh-cn:
#   languageCode: zh-CN
#   languageName: "简体中文"
#   weight: 3

# ja:
#   languageCode: ja-JP
#   languageName: "日本語"
#   weight: 4

fr:
  languageCode: fr-FR
  languageName: "Français"
  weight: 1

# de:
#   languageCode: de-DE
#   languageName: "Deutsch"
#   weight: 5

# es:
#   languageCode: es-ES
#   languageName: "Español"
#   weight: 6

# ru:
#   languageCode: ru-RU
#   languageName: "Русский"
#   weight: 7
